title: Clover-Clever
author: Sanghoon Lee
email: akdrhaktapfhs1@gmail.com
description: "모스펫 도둑입니다."

# ▶︎ 새 테마
remote_theme: YoussefRaafatNasry/portfolYOU

# 기본 URL
baseurl: ""           # 저장소가 <user>.github.io 이면 그대로
url: "https://clover-clever.github.io"

# 사용 플러그인
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num"
